name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? This issue may be closed if no further activity occurs.
            Thank you for your contributions.
          close-issue-message: |
            Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
          days-before-issue-stale: 90
          days-before-issue-close: 7
          stale-issue-label: 'Stale'
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
          close-pr-message: |
            This pull request has been closed due to inactivity. If you would like to continue working on this, please reopen the pull request or create a new one.
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-label: 'Stale'
          exempt-issue-labels: 'pinned,security,bug'
          exempt-pr-labels: 'pinned,security'
          operations-per-run: 30
